# Generated by Django 2.1.7 on 2019-03-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190305_0745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articlc',
            new_name='Article',
        ),
    ]
